project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('recipes.urls')),
    path('', RedirectView.as_view(url='/recipes/', permanent=True)),
    path('home/', RedirectView.as_view(url='/recipes/', permanent=True)),
    path('index/', RedirectView.as_view(url='/recipes/', permanent=True))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('recipes.urls')),
    path('', RedirectView.as_view(url='/recipes/', permanent=True)),
    path('home/', RedirectView.as_view(url='/recipes/', permanent=True)),
    path('index/', RedirectView.as_view(url='/recipes/', permanent=True))
]

recipes/urls.py
from django.contrib import admin
from django.urls import path
from recipes.views import home, contact, about, recipe

app_name = 'recipes'

urlpatterns = [
    path('', home, name='default'),
    path('home/', home, name='home'),
    path('index/', home, name='index'),
    path('contact/', contact),
    path('about/', about),
    path('<int:id>/', recipe, name='detail'),
    # path('category/<int:id>/', home)
]

recipes/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django.conf import settings
import uuid


class Category(models.Model):
    name = models.CharField(max_length=65, verbose_name=_("Nome"))
    # slug = models.SlugField(unique=True, max_length=65)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)
        
    def __str__(self):
        return self.name
    
    class Meta:
        db_table = "category"
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        

class Recipe(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    title = models.CharField(max_length=65, verbose_name=_("Título"))
    description = models.CharField(max_length=165, verbose_name=_("Descrição"))
    preparation_time = models.IntegerField(verbose_name=_("Tempo de Preparo"))
    # preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField(verbose_name=_("Quantidade de Porção"))
    # servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField(verbose_name=_("Texto"))
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/',
        verbose_name=_("Imagem")
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, verbose_name=_("Categoria")
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)
    
    class Meta:
        db_table = "recipe"
        verbose_name = "Receita"
        verbose_name_plural = "Receitas"
                


    

recipes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from utils.recipes.factory import make_recipe
from .models import Recipe
import pdb

def home(request, id=None):
    data = Recipe.objects.filter(status=1).order_by('-id')
        
    return render(request, 'pages/home.html', {
        'title': 'Home',
        'page': 'pages/home.html',
        'data': data
    }, None, 200, None)


def contact(request):
    return render(request, 'pages/contact.html', {
        'title': 'Contato',
        'page': 'pages/contact.html'
    }, None, 200, None)


def about(request):
    return render(request, 'pages/about.html', {
        'title': 'Sobre',
        'page': 'pages/about.html'
    }, None, 200, None)
    

def recipe(request, id:int):    
    data = Recipe.objects.filter(id=id, status=1).first()
        
    if not data:
        return redirect('/')
            
    return render(request, 'pages/recipe.html', {
        'title': 'Receita',
        'page': 'pages/recipe.html',
        'item': data
    }, None, 200, None)

templates/pages/about.html
{% extends "view.html" %}
{% block title %}{{title}}{% endblock title %}
{% load static %}

{% block content %}

{% endblock content %}

templates/pages/contact.html
{% extends "view.html" %}
{% block title %}{{title}}{% endblock title %}
{% load static %}

{% block content %}

{% endblock content %}

templates/pages/home.html
{% extends "view.html" %}
{% block title %}{{title}}{% endblock title %}
{% load static %} 

{% block content %}
    {% include '../partials/search.html' %}  

    {% if data %}
        <div class="main-content main-content-list container">
            {% for item in data %} 
                <div class="recipe recipe-list-item">
                    <div class="recipe-cover">
                        {% if item.cover %}
                            <img src="/media/{{item.cover}}" alt="Temporário">
                        {% else %}
                            <img src="{% static 'img/default.png'%}" alt="Temporário">
                        {% endif %}
                    </div>
                    <div class="recipe-title-container">
                        <h3 class="recipe-title">{{ item.title }}</h3>
                    </div>

                    <div class="recipe-author">
                        <span class="recipe-author-item">
                            <i class="fas fa-calendar-alt"></i>
                            {{ item.created_at|date:"d/m/Y" }} às {{item.created_at|date:"H:i:s"}}
                        </span>

                        <span class="recipe-author-item">
                            <a href="/recipes/category/{{item.category.id}}">
                                <i class="fas fa-layer-group"></i>
                                <span>{{item.category.name}}</span>
                            </a>
                        </span>
                    </div>

                    <div class="recipe-content">
                        <p>{{item.description}}</p>
                    </div>

                    <div class="recipe-meta-container">
                        <div class="recipe-meta recipe-preparation">
                            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
                            <div class="recipe-meta-text">
                                {{item.preparation_time}} Minuto(s)
                            </div>
                        </div>
                        <div class="recipe-meta recipe-servings">
                            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
                            <div class="recipe-meta-text">
                                {{item.servings}} 
                                {% if item.servings > 1 %}
                                    Porções
                                {% else %}
                                    Porção
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <footer class="recipe-footer">
                        <a class="recipe-read-more button button-dark button-full-width" href="/recipes/{{item.id}}/">
                            <i class="fas fa-eye"></i>
                            <span>ver mais...</span>
                        </a>
                    </footer>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="container">
            <div class="alert alert-warning" role="alert">
                <h4 class="alert-heading">Atenção!</h4>
                <p>No momento, não há receitas cadastradas no site.</p>
                <hr>
                <p class="mb-0">Pedimos desculpas pelo ocorrido. Por favor, volte novamente mais tarde...</p> 
            </div>
        </div>
    {% endif %} 
{% endblock content %} 

templates/pages/recipe.html
{% extends "view.html" %}
{% block title %}{{title}}{% endblock title %}
{% load static %}

{% block content %}
    <main class="main-content-container">
        <div class="main-content main-content-detail container">
            <div class="recipe recipe-list-item">
                <div class="recipe-cover">
                    {% if item.cover %}
                        <img src="/media/{{item.cover}}" alt="Temporário" style="width: 100%!important;">
                    {% else %}
                        <img src="{% static 'img/default.png'%}" alt="Temporário">
                    {% endif %} 
                </div>
                
                <div class="recipe-title-container">
                    <h3 class="recipe-title">{{ item.title }}</h3>
                </div>

                <div class="recipe-author">
                    <span class="recipe-author-item">
                        <i class="fas fa-calendar-alt"></i>
                        {{ item.created_at|date:"d/m/Y" }} às {{item.created_at|date:"H:i:s"}}
                    </span>

                    <span class="recipe-author-item">
                        <a href="/recipes/category/{{item.category.id}}">
                            <i class="fas fa-layer-group"></i>
                            <span>{{item.category.name}}</span>
                        </a>
                    </span>
                </div>

                <div class="recipe-content">
                    <p>{{item.preparation_steps|linebreaksbr}}</p>
                </div>

                <div class="recipe-meta-container">
                    <div class="recipe-meta recipe-preparation">
                        <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
                        <div class="recipe-meta-text">
                            {{item.preparation_time}} Minuto(s)
                        </div>
                    </div>
                    <div class="recipe-meta recipe-servings">
                        <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
                        <div class="recipe-meta-text">
                            {{item.servings}} 
                            {% if item.servings > 1 %}
                                Porções
                            {% else %}
                                Porção
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %} 

templates/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Admin</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

templates/partials/head.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link 
        rel="stylesheet" 
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css" 
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A==" 
        crossorigin="anonymous" 
        referrerpolicy="no-referrer" 
    />
    <link 
        rel="stylesheet" 
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css" 
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ==" 
        crossorigin="anonymous" 
        referrerpolicy="no-referrer" 
    />
    <link 
        rel="stylesheet" 
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css" 
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w==" 
        crossorigin="anonymous" 
        referrerpolicy="no-referrer" 
    />
    {% load static %}
    
    {% comment %} partials-CSS {% endcomment %}
    <link rel="stylesheet" href="{% static '/css/header.css' %}">
    <link rel="stylesheet" href="{% static '/css/view.css' %}">
    <link rel="stylesheet" href="{% static '/css/footer.css' %}">

    {% comment %} pages-CSS {% endcomment %}
    <link rel="stylesheet" href="{% static '/css/home.css' %}">
</head>

templates/partials/header.html
<header>
    <div class="main-header-container">
        <div class="main-header container" style="padding-top: 15px; padding-bottom: 15px;">
            <h1>
                <a class="main-logo" href="{% url 'recipes:home' %}">
                    {% load static %}
                    <img src="{% static "img/header.png" %}" alt="Avatar" style="width:100px;">

                    <span class="main-logo-text" style="font-size: 40px; padding-left: 10px;">
                        Receitas da Rob
                    </span>
                </a>
            </h1>
        </div>
    </div>
</header>

templates/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>

templates/view.html
<!DOCTYPE html>
<html lang="en">
    {% comment %} {% include "partials/head.html" %}  {% endcomment %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} {% endblock title %}</title>
        <link rel="icon" type="image/x-icon" href="/favicon.ico">
        <link 
            rel="stylesheet" 
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css" 
            integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A==" 
            crossorigin="anonymous" 
            referrerpolicy="no-referrer" 
        />
        <link 
            rel="stylesheet" 
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css" 
            integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ==" 
            crossorigin="anonymous" 
            referrerpolicy="no-referrer" 
        />
        <link 
            rel="stylesheet" 
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css" 
            integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w==" 
            crossorigin="anonymous" 
            referrerpolicy="no-referrer" 
        />
        {% load static %}
        
        {% comment %} partials-CSS {% endcomment %}
        <link rel="stylesheet" href="{% static '/css/header.css' %}">
        <link rel="stylesheet" href="{% static '/css/view.css' %}">
        <link rel="stylesheet" href="{% static '/css/footer.css' %}">
    
        {% comment %} pages-CSS {% endcomment %}
        <link rel="stylesheet" href="{% static '/css/home.css' %}">
    </head>

    <body>
        {% include "partials/header.html" %} 
        <main class="main-content-container"> 
            {% block content %} {% endblock content %} 
        </main> 
    </body>
    
    {% include "partials/footer.html" %} 
</html>